<a href="https://colab.research.google.com/github/manasvisrivastava-25BAI/EDA-LAB/blob/main/eda_lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [8]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Airpassengers.csv')

In [9]:
#first five entries
df.head()

     Month  #Passengers
0  1949-01          112
1  1949-02          118
2  1949-03          132
3  1949-04          129
4  1949-05          121

In [10]:
#last five entries
df.tail()

       Month  #Passengers
139  1960-08          606
140  1960-09          508
141  1960-10          461
142  1960-11          390
143  1960-12          432

In [13]:
df.dtypes

Month          object
#Passengers     int64
dtype: object

In [14]:
df.describe()

       #Passengers
count   144.000000
mean    280.298611
std     119.966317
min     104.000000
25%     180.000000
50%     265.500000
75%     360.500000
max     622.000000

In [18]:
df[df['#Passengers']>300]

       Month  #Passengers
66   1954-07          302
77   1955-06          315
78   1955-07          364
79   1955-08          347
80   1955-09          312
..       ...          ...
139  1960-08          606
140  1960-09          508
141  1960-10          461
142  1960-11          390
143  1960-12          432

[62 rows x 2 columns]

In [19]:
df.nlargest(10, '#Passengers')

       Month  #Passengers
138  1960-07          622
139  1960-08          606
127  1959-08          559
126  1959-07          548
137  1960-06          535
140  1960-09          508
115  1958-08          505
114  1958-07          491
125  1959-06          472
136  1960-05          472

In [20]:
df['#Passengers'].max()

622

In [21]:
df['#Passengers'].min()

104

In [22]:
df.rename(columns={'#Passengers':'Passengers'}, inplace=True)

In [23]:
print(df.columns)

Index(['Month', 'Passengers'], dtype='object')