<a href="https://colab.research.google.com/github/manasvisrivastava-25BAI/EDA-LAB/blob/main/exp5_04_08_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [56]:
import pandas as pd
import numpy as np
df1 = pd.read_csv('/content/drive/MyDrive/fraudTest.csv')
df2 = pd.read_csv('/content/drive/MyDrive/fraudTrain.csv')

In [57]:
marks = [120, 132, 154, 164, 168, 177, 189, 190, 193, 194, 194, 197, 199, 200]
bins  = [118, 125, 160, 180, 200]
category = pd.cut(marks, bins)
category

[(118, 125], (125, 160], (125, 160], (160, 180], (160, 180], ..., (180, 200], (180, 200], (180, 200], (180, 200], (180, 200]]
Length: 14
Categories (4, interval[int64, right]): [(118, 125] < (125, 160] < (160, 180] < (180, 200]]

In [58]:
pd.value_counts(category)

/tmp/ipykernel_754/2654243906.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(category)

(180, 200]    8
(160, 180]    3
(125, 160]    2
(118, 125]    1
Name: count, dtype: int64

In [59]:
bin_names = ['low', 'average', 'high', 'excellent']
pd.cut(marks, bins, labels=bin_names)

['low', 'average', 'average', 'high', 'high', ..., 'excellent', 'excellent', 'excellent', 'excellent', 'excellent']
Length: 14
Categories (4, object): ['low' < 'average' < 'high' < 'excellent']

In [60]:
pd.cut(np.random.rand(40), 5, precision=2)

[(0.39, 0.57], (0.21, 0.39], (0.76, 0.94], (0.025, 0.21], (0.025, 0.21], ..., (0.57, 0.76], (0.39, 0.57], (0.21, 0.39], (0.025, 0.21], (0.21, 0.39]]
Length: 40
Categories (5, interval[float64, right]): [(0.025, 0.21] < (0.21, 0.39] < (0.39, 0.57] <
                                           (0.57, 0.76] < (0.76, 0.94]]

In [61]:
randomNumbers = np.random.rand(2000)
category3 = pd.qcut(randomNumbers, 4)
category3

[(-0.000758, 0.251], (0.745, 1.0], (-0.000758, 0.251], (0.251, 0.509], (0.745, 1.0], ..., (-0.000758, 0.251], (0.745, 1.0], (0.745, 1.0], (0.509, 0.745], (-0.000758, 0.251]]
Length: 2000
Categories (4, interval[float64, right]): [(-0.000758, 0.251] < (0.251, 0.509] < (0.509, 0.745] <
                                           (0.745, 1.0]]

In [62]:
pd.value_counts(category3)

/tmp/ipykernel_754/647498483.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(category3)

(-0.000758, 0.251]    500
(0.251, 0.509]        500
(0.509, 0.745]        500
(0.745, 1.0]          500
Name: count, dtype: int64

In [63]:
df1.head(10)

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,40.6729,-73.5365,34496,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,28.5697,-80.8191,54767,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,44.2529,-85.0170,1126,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0
5,5,2020-06-21 12:15:37,30407675418785,fraud_Daugherty LLC,kids_pets,19.55,Danielle,Evans,F,76752 David Lodge Apt. 064,...,42.1939,-76.7361,520,Psychotherapist,1991-10-13,798db04aaceb4febd084f1a7c404da93,1371816937,41.747157,-77.584197,0
6,6,2020-06-21 12:15:44,213180742685905,fraud_Romaguera Ltd,health_fitness,133.93,Kayla,Sutton,F,010 Weaver Land,...,40.5070,-123.9743,1139,"Therapist, occupational",1951-01-15,17003d7ce534440eadb10c4750e020e5,1371816944,41.499458,-124.888729,0
7,7,2020-06-21 12:15:50,3589289942931264,fraud_Reichel LLC,personal_care,10.37,Paula,Estrada,F,350 Stacy Glens,...,43.7557,-97.5936,343,"Development worker, international aid",1972-03-05,8be473af4f05fc6146ea55ace73e7ca2,1371816950,44.495498,-97.728453,0
8,8,2020-06-21 12:16:10,3596357274378601,"fraud_Goyette, Howell and Collier",shopping_pos,4.37,David,Everett,M,4138 David Fall,...,41.0001,-78.2357,3688,Advice worker,1973-05-27,71a1da150d1ce510193d7622e08e784e,1371816970,41.546067,-78.120238,0
9,9,2020-06-21 12:16:11,3546897637165774,fraud_Kilback Group,food_dining,66.54,Kayla,Obrien,F,7921 Robert Port Suite 343,...,31.6591,-96.8094,263,Barrister,1956-05-30,a7915132c7c4240996ba03a47f81e3bd,1371816971,31.782919,-96.366185,0

In [64]:
df2.head(10)

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0
5,5,2019-01-01 00:04:08,4767265376804500,"fraud_Stroman, Hudson and Erdman",gas_transport,94.63,Jennifer,Conner,F,4655 David Island,...,40.3750,-75.2045,2158,Transport planner,1961-06-19,189a841a0a8ba03058526bcfe566aab5,1325376248,40.653382,-76.152667,0
6,6,2019-01-01 00:04:42,30074693890476,fraud_Rowe-Vandervort,grocery_net,44.54,Kelsey,Richards,F,889 Sarah Station Suite 624,...,37.9931,-100.9893,2691,Arboriculturist,1993-08-16,83ec1cc84142af6e2acf10c44949e720,1325376282,37.162705,-100.153370,0
7,7,2019-01-01 00:05:08,6011360759745864,fraud_Corwin-Collins,gas_transport,71.65,Steven,Williams,M,231 Flores Pass Suite 720,...,38.8432,-78.6003,6018,"Designer, multimedia",1947-08-21,6d294ed2cc447d2c71c7171a3d54967c,1325376308,38.948089,-78.540296,0
8,8,2019-01-01 00:05:18,4922710831011201,fraud_Herzog Ltd,misc_pos,4.27,Heather,Chase,F,6888 Hicks Stream Suite 954,...,40.3359,-79.6607,1472,Public affairs consultant,1941-03-07,fc28024ce480f8ef21a32d64c93a29f5,1325376318,40.351813,-79.958146,0
9,9,2019-01-01 00:06:01,2720830304681674,"fraud_Schoen, Kuphal and Nitzsche",grocery_pos,198.39,Melissa,Aguilar,F,21326 Taylor Squares Suite 708,...,36.5220,-87.3490,151785,Pathologist,1974-03-28,3b9014ea8fb80bd65de0b1463b00b00e,1325376361,37.179198,-87.485381,0

In [65]:
df1['fine'] = df1['amt'] * 2.0
df1

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud,fine
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0,5.72
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0,59.68
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,-73.5365,34496,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0,82.56
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,-80.8191,54767,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0,120.10
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,-85.0170,1126,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0,6.38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555714,555714,2020-12-31 23:59:07,30560609640617,fraud_Reilly and Sons,health_fitness,43.77,Michael,Olson,M,558 Michael Estates,...,-91.8912,519,Town planner,1966-02-13,9b1f753c79894c9f4b71f04581835ada,1388534347,39.946837,-91.333331,0,87.54
555715,555715,2020-12-31 23:59:09,3556613125071656,fraud_Hoppe-Parisian,kids_pets,111.84,Jose,Vasquez,M,572 Davis Mountains,...,-95.4401,28739,Futures trader,1999-12-27,2090647dac2c89a1d86c514c427f5b91,1388534349,29.661049,-96.186633,0,223.68
555716,555716,2020-12-31 23:59:15,6011724471098086,fraud_Rau-Robel,kids_pets,86.88,Ann,Lawson,F,144 Evans Islands Apt. 683,...,-118.9017,3684,Musician,1981-11-29,6c5b7c8add471975aa0fec023b2e8408,1388534355,46.658340,-119.715054,0,173.76
555717,555717,2020-12-31 23:59:24,4079773899158,fraud_Breitenberg LLC,travel,7.99,Eric,Preston,M,7020 Doyle Stream Apt. 951,...,-116.4493,129,Cartographer,1965-12-15,14392d723bb7737606b2700ac791b7aa,1388534364,44.470525,-117.080888,0,15.98
555718,555718,2020-12-31 23:59:34,4170689372027579,fraud_Dare-Marvin,entertainment,38.13,Samuel,Frey,M,830 Myers Plaza Apt. 384,...,-97.4798,116001,Media buyer,1993-05-10,1765bb45b3aa3224b4cdcb6e7a96cee3,1388534374,36.210097,-97.036372,0,76.26

In [66]:
df2['fine '] = df1['amt']*3.25
df2

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud,fine
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0,9.2950
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0,96.9800
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0,134.1600
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0,195.1625
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0,10.3675
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1296670,1296670,2020-06-21 12:12:08,30263540414123,fraud_Reichel Inc,entertainment,15.56,Erik,Patterson,M,162 Jessica Row Apt. 072,...,-112.4777,258,Geoscientist,1961-11-24,440b587732da4dc1a6395aba5fb41669,1371816728,36.841266,-111.690765,0,NaN
1296671,1296671,2020-06-21 12:12:19,6011149206456997,fraud_Abernathy and Sons,food_dining,51.70,Jeffrey,White,M,8617 Holmes Terrace Suite 651,...,-77.5101,100,"Production assistant, television",1979-12-11,278000d2e0d2277d1de2f890067dcc0a,1371816739,38.906881,-78.246528,0,NaN
1296672,1296672,2020-06-21 12:12:32,3514865930894695,fraud_Stiedemann Ltd,food_dining,105.93,Christopher,Castaneda,M,1632 Cohen Drive Suite 639,...,-105.8189,899,Naval architect,1967-08-30,483f52fe67fabef353d552c1e662974c,1371816752,33.619513,-105.130529,0,NaN
1296673,1296673,2020-06-21 12:13:36,2720012583106919,"fraud_Reinger, Weissnat and Strosin",food_dining,74.90,Joseph,Murray,M,42933 Ryan Underpass,...,-102.5411,1126,Volunteer coordinator,1980-08-18,d667cdcbadaaed3da3f4020e83591c83,1371816816,42.788940,-103.241160,0,NaN
1296674,1296674,2020-06-21 12:13:37,4292902571056973207,"fraud_Langosh, Wintheiser and Hyatt",food_dining,4.30,Jeffrey,Smith,M,135 Joseph Mountains,...,-113.8748,218,"Therapist, horticultural",1995-08-16,8f7c8e4ab7f25875d753b422917c98c9,1371816817,46.565983,-114.186110,0,NaN

In [67]:
totalfine = df1["fine"]
totalfine[np.abs(totalfine)>200]

6         267.86
30        352.46
31        268.78
33        420.72
37        269.20
           ...
555683    280.24
555696    330.78
555705    247.68
555707    268.52
555715    223.68
Name: fine, Length: 99985, dtype: float64

In [68]:
total = df2["fine "]
total[np.abs(total)>200]

6         435.2725
9         216.2550
18        260.3575
30        572.7475
31        436.7675
            ...
555702    268.1575
555705    402.4800
555707    436.3450
555715    363.4800
555716    282.3600
Name: fine , Length: 219491, dtype: float64

In [69]:
df1[np.abs(totalfine)>300]

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud,fine
30,30,2020-06-21 12:25:09,379897244598068,fraud_Kautzer and Sons,personal_care,176.23,Frank,Key,M,5537 Jessica Plaza,...,-85.4834,3263,Stage manager,1930-02-28,3f5587dd43e45910ba221bc3a4dfdd3f,1371817509,38.585316,-86.108185,0,352.46
33,33,2020-06-21 12:26:23,180036456789979,fraud_Nienow PLC,entertainment,210.36,Mackenzie,Salazar,F,982 Melissa Lock,...,-91.0685,878,Risk analyst,1974-11-20,902facfd912019350d63a3539990638e,1371817583,42.736666,-90.099710,0,420.72
67,67,2020-06-21 12:34:07,3502377050801561,fraud_Ziemann-Waters,health_fitness,181.87,Kathleen,Martin,F,659 Nicole Cove Suite 560,...,-95.4532,4993,"Scientist, biomedical",1948-11-30,a6dd646fb7f598d3545ade098183cbbd,1371818047,31.152375,-95.272196,0,363.74
71,71,2020-06-21 12:36:17,3590736522064285,fraud_Kihn Inc,shopping_pos,189.99,Kimberly,Gonzalez,F,72966 Shannon Pass Apt. 391,...,-92.4828,4074,"Scientist, audiological",1975-12-20,bb3889edf0a90703cc3e281322e9aef1,1371818177,34.442520,-92.264081,0,379.98
100,100,2020-06-21 12:45:48,6592074504369261,fraud_Greenholt Ltd,health_fitness,242.35,Amanda,Molina,F,8425 Daniel Knolls Suite 288,...,-74.9781,1526206,Commercial horticulturist,1972-05-23,39db7261e2dd32311c1e5ff2a52bac79,1371818748,39.151823,-75.035003,0,484.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555629,555629,2020-12-31 23:26:42,2248735346244816,fraud_Crooks and Sons,personal_care,302.79,Jacob,Weber,M,29156 Mark Park Apt. 108,...,-100.1380,269,Product/process development scientist,1962-11-11,f7a3967372c0d90e260927e69e787165,1388532402,37.949152,-99.766839,0,605.58
555637,555637,2020-12-31 23:30:29,6011109736646996,fraud_Gleason-Macejkovic,shopping_net,1164.37,Rebecca,Erickson,F,594 Berry Lights Apt. 392,...,-77.8670,186140,English as a second language teacher,1983-02-08,b7f83407df7234b10f7aa2c06af06444,1388532629,34.854212,-77.711814,0,2328.74
555647,555647,2020-12-31 23:32:24,6011438889172900,fraud_Auer-West,shopping_net,410.05,Allison,Allen,F,40624 Rebecca Spurs,...,-91.3336,5161,Electrical engineer,1993-04-08,ae7ac98245d7caab2c2fb8b1fac5afa2,1388532744,33.684449,-91.954633,0,820.10
555677,555677,2020-12-31 23:42:51,4189814094741,fraud_Frami Group,entertainment,176.87,Jason,Farmer,M,33165 Larry Walks Suite 960,...,-86.1619,4159,Educational psychologist,1998-02-03,16b2c9d8aad39f5acffbc83fbe6e41d9,1388533371,33.920429,-85.450060,0,353.74
555696,555696,2020-12-31 23:50:45,3568255211412877,fraud_Fritsch and Sons,health_fitness,165.39,Timothy,Gomez,M,707 Anthony Causeway,...,-85.0301,5341,Biomedical engineer,1994-11-24,7094b2fb1ffdd76e568700061d8bc407,1388533845,40.794699,-84.462716,0,330.78

In [70]:
df2[np.abs(total)>400]

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud,fine
6,6,2019-01-01 00:04:42,30074693890476,fraud_Rowe-Vandervort,grocery_net,44.54,Kelsey,Richards,F,889 Sarah Station Suite 624,...,-100.9893,2691,Arboriculturist,1993-08-16,83ec1cc84142af6e2acf10c44949e720,1325376282,37.162705,-100.153370,0,435.2725
30,30,2019-01-01 00:22:36,180094608895855,"fraud_Kihn, Abernathy and Douglas",shopping_net,3.66,Tammie,Harper,F,57887 Gutierrez Harbor,...,-122.4810,597,Forensic psychologist,1961-05-19,870c92b288a974a2faf1f24b05c27e33,1325377356,44.278191,-121.815161,0,572.7475
31,31,2019-01-01 00:22:39,4599735407877245080,"fraud_Heller, Gutmann and Zieme",grocery_pos,82.80,Mary,Myers,F,39787 Pamela Fall Suite 639,...,-89.4649,5577,Geochemist,1964-12-30,cb598ec00d349dc95e7b3c18de5ae800,1325377359,36.294205,-89.811282,0,436.7675
33,33,2019-01-01 00:23:41,2712209726293386,fraud_Balistreri-Nader,misc_pos,25.58,Jenna,Brooks,F,50872 Alex Plain Suite 088,...,-91.1468,378909,"Designer, furniture",1977-02-22,1654da2abfb9e79a5f99167fc9779558,1325377421,29.737426,-90.853194,0,683.6700
37,37,2019-01-01 00:27:45,213141712584544,fraud_Halvorson Group,misc_pos,181.35,Margaret,Curtis,F,742 Oneill Shore,...,-90.1217,19685,Fine artist,1984-12-24,7bb25a43205191eb7344282b88fc54d3,1325377665,31.939812,-90.726209,0,437.4500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555677,555677,2019-08-25 12:07:04,4653178848915023204,"fraud_Armstrong, Walter and Gottlieb",food_dining,15.87,Robert,Hall,M,371 Anthony Trail Suite 354,...,-81.7676,5657,Clinical psychologist,1987-04-29,f1e07e35f39829321eb15c84163237ac,1345896424,37.202063,-81.919503,0,574.8275
555683,555683,2019-08-25 12:09:33,373905417449658,fraud_Ernser-Lynch,food_dining,34.44,Sarah,Bishop,F,554 Mcdonald Valley Apt. 539,...,-97.6443,2526,Phytotherapist,1970-11-12,5578fd04e6941ac836f593385b3f6e8a,1345896573,32.685765,-97.487618,0,455.3900
555696,555696,2019-08-25 12:12:41,6595970453799027,fraud_Terry Ltd,home,28.96,Gina,Gomez,F,72030 Shelton Crossing Apt. 742,...,-74.4968,2307,Science writer,1969-09-11,3f9f9da0601f10e1bb4dac499a75941e,1345896761,40.023994,-75.055998,0,537.5175
555705,555705,2019-08-25 12:14:28,3596217206093829,fraud_Bruen-Yost,misc_pos,3.62,Sara,Ramirez,F,23843 Scott Island,...,-91.9534,888,Camera operator,1988-03-25,b0088859de4c9a072d5d72819b81c319,1345896868,39.972608,-92.634978,0,402.4800
555707,555707,2019-08-25 12:14:44,4570636521433188,"fraud_Feil, Hilpert and Koss",food_dining,33.18,Christine,Leblanc,F,5097 Jodi Vista Suite 811,...,-81.2473,88735,Commercial horticulturist,1988-04-09,d848fb606ea275bf2b8ce351ae407734,1345896884,29.104817,-82.135604,0,436.3450

In [71]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler

In [72]:
data = {'Age':[25,30,45,32,22], 'Salary':[50000, 64000, 1200000, 85000, 1200000]}
df = pd.DataFrame(data)
print("Orignal data : \n", df, "\n")

Orignal data :
    Age   Salary
0   25    50000
1   30    64000
2   45  1200000
3   32    85000
4   22  1200000

In [73]:
min_max_scaler = MinMaxScaler()
df_min_max = pd.DataFrame(min_max_scaler.fit_transform(df), columns=df.columns)
print("Min-Max Scaled Data:\n", df_min_max, "\n")

Min-Max Scaled Data:
         Age    Salary
0  0.130435  0.000000
1  0.347826  0.012174
2  1.000000  1.000000
3  0.434783  0.030435
4  0.000000  1.000000

In [74]:
standard_scaler = StandardScaler()
df_standard = pd.DataFrame(standard_scaler.fit_transform(df), columns = df.columns)
print("Standardized data:\n", df_standard, "\n")

Standardized data:
         Age    Salary
0 -0.730963 -0.845736
1 -0.100823 -0.820533
2  1.789600  1.224498
3  0.151234 -0.782729
4 -1.109048  1.224498